### PR TITLE
Remove enum MessageType in ProtoBuf

### PR DESCRIPTION
**Pull request by TomGneuss**
The ProtoBuf generator introduced an additonal enum called `MessageType`. It was intended to be used as identification of the concrete type of message that is used in a proto3 `oneof` construct. However, when compiling `*.proto` files, some identification mechanism is automatically introduced by the proto compiler. Thus, this enum is not required anymore.

### CODE REVIEW

**Comment by mristin** [comment]
@TomGneuss The CI is failing due to a depency, *i.e.* unrelated to this pull request. Let me please fix that first next week, then we'll run the CI to the end.

**Comment by TomGneuss** [comment]
Thank you for reviewing! Let me know if I can do anything to help

**Comment by mristin** [comment]
@TomGneuss I fixed the CI for forks in #486 . Could you please update your fork so that we can re-run the CI?

**Comment by mristin** [comment]
Thanks again, @TomGneuss !

**Pull request merged**
