### PR TITLE
JSON-LD trials

### PR DESCRIPTION
**Pull request by VladimirAlexiev**
@ethieblin @wiresio @mristin
Described in https://github.com/admin-shell-io/aas-specs/issues/386

### CODE REVIEW

**Comment by mristin** [comment]
@VladimirAlexiev as far as I can see, you haven't committed any changes to the generator? 

If I understand correctly, you want to manually change the JSON-LD instead of generating it? If so, then this repository is the wrong place. The aas-core-codegen is a transpiler. Please have a look at this module which implements the generation of JSON-LD from a formalized  meta-model:
https://github.com/aas-core-works/aas-core-codegen/blob/main/aas_core_codegen/jsonld/main.py

**Comment by VladimirAlexiev** [comment]
Hi @mristin ! 
I don't want to change the context manually, that's why my patched version is called `context-fixed.jsonld` 
and the trials in the README use this URL to access the context: https://rawgit2.com/VladimirAlexiev/aas-core-codegen/main/test_data/jsonld_context/context-fixed.jsonld .

Please merge the "trials" folder. It serves to document the round-tripping attempts, and the need for 2 changes to context.

**Comment by mristin** [comment]
@VladimirAlexiev 

> Hi @mristin ! I don't want to change the context manually, that's why my patched version is called `context-fixed.jsonld` [...]

Please double-check, have you forgotten maybe to add files to the commit? I only see changes to `test_data`, but no changes to `aas_core_codegen/json_ld/`.

The `test_data/` are the golden test files *recorded* during the unit tests. There is no point changing them manually.

**Comment by VladimirAlexiev** [comment]
@mristin Move `context-fixed.jsonld` into `trials/` and move that folder wherever it belongs best.
Cheers!

**Comment by mristin** [comment]
@VladimirAlexiev if there are no changes to the generator(s), then these files and documents simply don't belong to this repository.

I suggest you either 1) create a separate repository, or 2) sync with the corresponding IDTA workgroup and put the files in their shared folder.

**Comment by VladimirAlexiev** [comment]
@mristin So you have examples, and you have context, but you don't want to include examples of how the context works?
That's strange. How can you ensure the context (and possible future extensions of it) work as intended, except by exercising the examples?

An important part of the work on the GS1 EPCIS semantic representation was hundreds of examples. 
I generated JSON -> Turtle -> Diagrams, and we made sure the Turtle and Diagrams looked ok, and had what they were supposed to have. 
- https://github.com/gs1/EPCIS/tree/master/JSON
- https://github.com/gs1/EPCIS/tree/master/Turtle
- https://github.com/gs1/EPCIS/tree/master/Diagrams

In this way I diagnosed hundreds of problems in the proposed Context. See one big cluster in https://github.com/gs1/EPCIS/issues/307.

**Comment by mristin** [comment]
@VladimirAlexiev I'm not saying that the examples are unnecessary -- this repository is simply not the place for them. This repository contains the code for automatic generation of different artefacts based on a formalized meta-model (not necessarily an AAS meta-model!).

The examples are *not* the test data of the generators, but of the *generated* artefacts.

**Pull request closed without merging**
