### PR TITLE
Update AUTHORS

### PR DESCRIPTION
**Pull request by g1zzm0**
Add all authors from TUD who are involved in aas core works.

### CODE REVIEW

**Comment by mristin** [comment]
@g1zzm0 please list only people who comitted changes traceable to a commit. Neither Uwe nor Robert contributed anything directly to this repository, did they?

**Comment by mristin** [comment]
If you want to add them, please at least state clearly their contributions in the description.

**Comment by g1zzm0** [comment]
Of course they worked on it. In addition, the list above also contains names that have no commits.

**Comment by mristin** [comment]
Please list their contributions somewhere.

Which contributors did I list which lack commits?

**Comment by mristin** [comment]
I double-checked once more the list of authors in the commits:
```
~/workspace/aas-core-works/aas-core-codegen (main)
$ git log|grep "Author: "|sort|uniq
Author: ethieblin <63397169+ethieblin@users.noreply.github.com>
Author: Igor Garmaev <56840636+zrgt@users.noreply.github.com>
Author: Marko Ristin <marko.ristin@***.com>
Author: Marko Ristin <marko@***.ch>
Author: Murloc6 <881739+Murloc6@users.noreply.github.com>
Author: Nico Braunisch <nico.braunisch@***.de>
Author: s-heppner <mail@***.com>
Author: Tobias Langer <empwilli@***.com>
Author: Tobias Langer <tobias.langer@***.de>
Author: Tom Gneuß <26270643+TomGneuss@users.noreply.github.com>
```

I also checked for co-authored commits:
```
$ git log|grep "author"|sort|uniq
    Co-authored-by: Marko Ristin <marko.ristin@gmail.com>
    Co-authored-by: Nico Braunisch <nico.braunisch@tu-dresden.de>
    Co-authored-by: Tom Gneuß <tom.gneuss@tu-dresden.de>
```

**Pull request merged**
